### ISSUE TITLE
"clang-format: Unable to set locate clang-format tools."

### ISSUE THREAD

**Issue by amccreight** [emilio/clang-format-merge#2]
I'm not sure what exactly went wrong, but when I ran the script it just deleted the contents of every file and replaced it with the string "clang-format: Unable to set locate clang-format tools.". It would be nice if this error was detected and the operation aborted rather than just destroying my patch.

**Comment by emilio** [comment]
Looks like `./mach clang-format` doesn't download the needed bits if it's ran with the `-assume-filename` thing?

https://searchfox.org/mozilla-central/rev/47edbd91c43db6229cf32d1fc4bae9b325b9e2d0/python/mozbuild/mozbuild/mach_commands.py#2358

**Comment by amccreight** [comment]
clang-format wasn't installed on my system at all. I had already run mach bootstrap, so I'm not sure why.

**Comment by emilio** [comment]
@amccreight I just uninstalled stuff and you need to run `./mach clang-format` manually, in order to get them... That's really unfortunate.

**Comment by amccreight** [comment]
Thanks!
